[package]
name = "thermal-printer-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bmp = "0.5.0"
escpos = { version = "0.17.0", features = ["full"] }
image = "0.25.9"
log = "0.4.29"
simple_logger = "5.1.0"
